# The main purpose of this plugin is to disable selected blocks from being affected by pistons. 
# This is useful to nerf farms or disable flying machines altogether.

# After changing config, run command "/pn reload" in game or in console to finalize the changes.

# This option enables or disables pistons from interacting with the configurable ist of blocks.
disable_piston_by_block: true

# Add or Remove blocks. Use the following link as guidance for formatting block names
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
disabled_blocks:
  - PUMPKIN
  - CARVED_PUMPKIN
  - MELON
  - SUGAR_CANE
  - BAMBOO_SAPLING
  - BAMBOO

# Please note that a single bamboo shoot in the ground is classified as BAMBOO_SAPLING.
# A bamboo shoot that has grown two blocks or higher is classified as BAMBOO.

# This option enables or disables honey and slime blocks from interacting with the configurable list of blocks.
disable_slime_honey_interaction_by_block: true

# Determines if slime and honey blocks can interact with crop blocks
disabled_slime_honey_interactions:
  - PUMPKIN
  - CARVED_PUMPKIN
  - MELON
  - SUGAR_CANE
  - BAMBOO_SAPLING
  - BAMBOO

# When set to false, disabled pistons will stay where they are placed, and simply not work to break any disabled blocks. 
# When set to true, disabled pistons will break upon attempted firing. 
break_piston_on_disable: false

# When set to true, pistons will drop to the ground if broken by the plugin.
# When se to false, pistons will disappear if broken by the plugin. 
drop_piston_on_break: true

# When true, allows minecarts pushed by slime or honey blocks to interact with blocks otherwise restricted
allow_minecart_interactions: false

# Enable anti-dispenser
anti-dispenser-enable: true

# List of disabled dispenser materials
disabled-dispenser-items:
  - BONE_MEAL

# List of disabled blocks to be affected by dispensers.
disabled-dispenser-blocks:
  - GRASS_BLOCK
  - PUMPKIN_STEM
  - MELON_STEM
  - CARROTS
  - POTATOES
  - WHEAT

# Enable anti-observer
anti-observer-enable: false
# List of blocks that cannot trigger observers when anti-observer-enable is set to true.
disabled-observer-blocks:
  - SUGAR_CANE
  - BAMBOO
