name: Pistonerf
version: '1.0'
main: com.bluah.pistonerf.Main
api-version: 1.20
authors: [ Bluah ]
description: Modifies piston behavior based on configured settings

commands:
  pistonerf:
    description: Manages Pistonerf configuration settings.
    usage: |
      /pistonerf reload - Reloads the configuration.
      /pistonerf list - Lists all disabled blocks.
      /pistonerf add blocks <material> - Adds a block to the disabled blocks list.
      /pistonerf remove blocks <material> - Removes a block from the disabled blocks list.
      /pistonerf add slime_honey <material> - Adds a block to the disabled slime/honey interactions list.
      /pistonerf remove slime_honey <material> - Removes a block from the disabled slime/honey interactions list.
    aliases: [pn]

permissions:
  pistonerf.reload:
    description: Allows reloading the Pistonerf configuration.
    default: op
  pistonerf.modify:
    description: Allows modifying the list of disabled blocks and slime/honey interactions.
    default: op
