name: Pistonerf
version: '1.0'
main: com.bluah.pistonerf.Main
api-version: 1.20
authors: [ Bluah ]
description: Modifies piston behavior based on configured settings

commands:
  pistonerf:
    description: Allows players to add or remove materials from the config, and list disabled materials.
    usage: /pistonerf add|remove|reload|list <material>
    aliases: [pn]

permissions:
  pistonerf.reload:
    description: Allows reloading the Pistonerf configuration
    default: op
  pistonerf.modify:
    description: Allows modifying the list of disabled blocks
    default: op
