name: Pistonerf
version: '1.0'
main: com.bluah.pistonerf.Main
api-version: 1.20
authors: [Bluah]
description: Modifies piston behavior based on configured settings.

commands:
  pistonerf:
    description: Reloads the Pistonerf plugin configuration.
    usage: /<command> reload
    aliases: [pn]
    permission: pistonerf.reload
    permission-message: You do not have permission to perform this command.

permissions:
  pistonerf.reload:
    description: Allows reloading the Pistonerf configuration.
    default: op
